package org.gjs.java.test.sample.model;
// Generated 13-abr-2022 10:36:11 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.Getter;
import lombok.Setter;

/**
 * Rol generated by hbm2java
 */
@Getter
@Setter
@Entity
@Table(name = "SAMPLE_WITHFK_ENTITY")
public class SampleWithFKEntity {

	@Id
	@Column(precision = 10)
	private Long id;

	@Column(name = "NOMBRE", unique = true, nullable = false, length = 50)
	private String nombre;

	@Column(name = "DESCRIPCION", nullable = false, length = 250)
	private String descripcion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_ALTA", nullable = false, length = 7)
	private Date fechaAlta;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_BAJA", length = 7)
	private Date fechaBaja;

	@Column(name = "ACTIVO", nullable = false, precision = 1, scale = 0)
	private Boolean activo;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SAMPLE_ID", nullable = false)
	private SampleEntity sample;

	public SampleWithFKEntity() {
	}

	@Override
	public String toString() {
		return "SampleWithFK [id=" + id + ", nombre=" + nombre + ", descripcion=" + descripcion + ", fechaAlta="
				+ fechaAlta + ", fechaBaja=" + fechaBaja + ", activo=" + activo + ", sample=" + sample + "]";
	}

}
