
#ifndef _ORG_GJS_C_CC_C_COMMON_TYPES_CONSTANTES_H
#define _ORG_GJS_C_CC_C_COMMON_TYPES_CONSTANTES_H





#define TIP_MAX_TAM_VARIABLE				255
#define TIP_MAX_TAM_VALOR					255

#define BUF_TAM_DEFECTO						256
#define BUF_MAX_TAM							268435456


#define ARB_MAX_HIJOS_NODO					65536
#define ARB_TAM_BLOQUE_HIJOS_NODO			256
#define ARB_NUM_BLOQUES_HIJOS_NODO			(ARB_MAX_HIJOS_NODO/ARB_TAM_BLOQUE_HIJOS_NODO)

#define GRAF_MAX_NODOS						2000
#define GRAF_MAX_ARISTAS_NODO				5

#define CONT_MAX_DIGITOS					16384

#define DAT_TAM_INICIAL_DEF					BUF_TAM_DEFECTO
#define DAT_TAM_BLOQUE_DEF					BUF_TAM_DEFECTO






#endif


