#ifndef _ORG_GJS_C_CC_C_TEST_RESULTADO_CASO_TEST_H
#define _ORG_GJS_C_CC_C_TEST_RESULTADO_CASO_TEST_H



#define RESULTADO_CASO_TEST_OK 			0
#define RESULTADO_CASO_TEST_KO			1
#define RESULTADO_CASO_TEST_FAIL		2

 
#endif